version: '3'

services:
  minio:
    image: minio/minio
    command: 'server --console-address ":9001" /data'
    environment:
      MINIO_ROOT_USER: postmaster@jbuget.fr
      MINIO_ROOT_PASSWORD: je4uMfNkjJBB2FTR3gN4
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
      
volumes:
  minio_storage: {}
